name: CI

on:
  push:
    branches: [ main, master, unittests ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs: {}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build tools and dependencies
      run: |
        python -m pip install --upgrade pip build
        pip install .[dev]
        pip install flake8

    - name: Lint code with flake8
      run: |
        flake8 src/multimodalrouter tests

    - name: Run tests
      run: |
        pytest


